set_property SRC_FILE_INFO {cfile:C:/Users/Micha/OneDrive/Documents/Learning/GT_Verilog/001_wires/001_wires.srcs/constrs_1/imports/Xilinx/Basys_3_Master.xdc rfile:../../../001_wires.srcs/constrs_1/imports/Xilinx/Basys_3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {i_sw}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {o_led}]
