set_property SRC_FILE_INFO {cfile:C:/Users/Micha/OneDrive/Documents/Learning/GT_Verilog/002_registers/002_registers.srcs/constrs_1/imports/Xilinx/Basys_3_Master.xdc rfile:../../../002_registers.srcs/constrs_1/imports/Xilinx/Basys_3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports i_clk]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {o_led}]
